# Generated by Django 5.0.2 on 2024-03-02 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_booking', '0002_alter_booking_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='seats_booked',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
